Cg/lab2 implementation
Ppasha9/gpu-labs pull request #2
Opened 2021-03-01 20:05 UTC by Ppasha9

2021-03-02 12:03 UTC, anthark requested changes
В целом хорошо. Даже управление удобное =)

Но, все-таки, есть замечания. 

1) По сцене не видно, что алгоритм реально работает. Все источники света имеют малую интенсивность и не пересекаются друг с другом. В итоге, нигде нет проблемы, которую, собственно, HDR решает. Сделайте с этим что-нибудь, пожалуйста. 

2) Большое количество warning'ов и error'ов. Исправьте, пожалуйста. Можно Включить break на них, тогда приложение будет сразу валится в нужных местах. 

3) При выходе остается много неудаленных объектов. Что особенно удивительно с учетом того, что вы используете автоуказатели. Исправьте, пожалуйста.

2021-03-02 12:03 UTC, anthark commented on anim/LogCopyTexturePixelShader.hlsl
> +    return log(p) + 1;
Хм... Какое число получится, если p == float4(0,0,0,0) ?

2021-03-08 12:27 UTC, pv6 commented on anim/LogCopyTexturePixelShader.hlsl
> +    return log(p) + 1;
Исправил на log(p + 1). Эта ошибка взялась со слайда про уменьшающиеся текстуры (сл. 37), там написана неправильная формула.

2021-03-08 15:53 UTC, pv6 commented
Исправил замечания.

Переключение яркости источников теперь на цифры 1, 2, 3.

2021-03-09 09:19 UTC, anthark commented on anim/LogCopyTexturePixelShader.hlsl
> +    return log(p) + 1;
Спасибо. Поправлю. То-то я смотрю, у всех одна и та же ошибка =)

2021-03-09 09:20 UTC, merged