Cg/lab3
Ppasha9/gpu-labs pull request #3
Opened 2021-03-11 17:42 UTC by pv6

Цифры 1, 2 - яркость источников (на 3 источника написал слишком много команд на один шейдер)
3 - обычный рендеринг
4 - Normal Distribution function
5 - Geometry function
6 - Fresnel function

2021-03-11 19:56 UTC, anthark requested changes
Почти идеально. 

Есть одна серьезная проблема, которую я попрошу вас поправить, остальное - просто советы.

2021-03-11 19:56 UTC, anthark commented on anim/Content/FresnelPixelShader.hlsl
> +    return float4(fresnel(
Здесь может получится (и получается =) ) странный результат, что эффект Френеля дает яркое пятно на поверхности, когда источник света светит на поверхность сзади. В полном шейдере это будет компенсировано значением dot(n,wi), но лучше все такие значения все-таки всегда клампить, поскольку иначе они могут неожиданно дать странные эффекты в совершенно другом месте, и придется долго и мучительно искать, что не так.

2021-03-11 19:56 UTC, anthark commented on anim/Content/PBRInclude.cginc
> +    return normalize((wi + wo) / 2);
Здесь можно на 2 не делить - все равно вектор будет нормализован. Скорее всего, шейдерный компилятор и сам это деление уберет, но без него исходный код шейдера будет выглядеть более профессионально

2021-03-11 19:56 UTC, anthark commented on anim/Content/PBRPixelShader.hlsl
> +        albedo * 0.56f +
Это аналог ambient, если я правильно понял?

2021-03-11 19:56 UTC, anthark commented on anim/Content/Sample3DSceneRenderer.cpp
> +        numLatitudeLines = 128,
Единственная серьезная проблема: если параметры поставить 16 и 16, например, пятно света будет выглядеть... неправильно. Какую длину имеет вектор, полученный линейной интерполяцией двух единичных векторов?

2021-03-12 11:03 UTC, pv6 commented on anim/Content/FresnelPixelShader.hlsl
> +    return float4(fresnel(
Исправлено

2021-03-12 11:03 UTC, pv6 commented on anim/Content/PBRInclude.cginc
> +    return normalize((wi + wo) / 2);
Исправлено

2021-03-12 11:04 UTC, pv6 commented on anim/Content/Sample3DSceneRenderer.cpp
> +        numLatitudeLines = 128,
Не подумал об этом, добавил нормализацию нормали

2021-03-12 11:08 UTC, pv6 commented on anim/Content/PBRPixelShader.hlsl
> +        albedo * 0.56f +
Да, простенький ambient lighting, чтобы естественнее смотрелось

2021-03-12 14:31 UTC, merged